server:
  port: 10001
spring:
  application:
    name: itrip-search-provider
  data:
    solr:
      host: http://localhost:8080/solr
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka/